//  Copyright 2013 Walter Schulze
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

/* Lexer Part */

_lineComment : '/' '/' {.} '\n' ;

_blockComment : '/' '*' {. | '*'} '*' '/' ;

!comment : _lineComment | _blockComment ;

!whitespace : ' ' | '\t' | '\n' | '\r' ;

_digit : '0'-'9' ;

int_lit : ['-'] _digit { _digit } ;

_upcase : 'A'-'Z' ;
_lowcase : 'a'-'z' ;

_id_char : _upcase | _lowcase | '_' | _digit ;

id : (_upcase | _lowcase | '_' ) {_id_char} ;

_hex_digit : '0' - '9' | 'A' - 'F' | 'a' - 'f';
_octal_digit : '0' - '7' ;

_big_u_value      : '\\' 'U' _hex_digit _hex_digit _hex_digit _hex_digit
                            _hex_digit _hex_digit _hex_digit _hex_digit ;
_little_u_value   : '\\' 'u' _hex_digit _hex_digit _hex_digit _hex_digit ;
_hex_byte_u_value   : '\\' 'x' _hex_digit _hex_digit ;
_escaped_char     : '\\' ( 'a' | 'b' | 'f' | 'n' | 'r' | 't' | 'v' | '\\' | '\'' | '"' ) ;

_octal_byte_u_value : '\\' _octal_digit _octal_digit _octal_digit ;
_byte_value       : _octal_byte_u_value | _hex_byte_u_value ;
_unicode_value    : . | _little_u_value | _big_u_value | _escaped_char ;

// char_lit	: '\'' (_unicode_value | _byte_value) '\'' ;

_raw_string : '`' {.} '`' ;
_interpreted_string : '"' { _unicode_value | _byte_value } '"' ;

string_lit : _raw_string | _interpreted_string ;

/* Syntax Part */

<< 
import (
	"github.com/awalterschulze/katydid/exp/find/ast"
	"code.google.com/p/gogoprotobuf/proto"
)
>>

Rules
	: Rules Rule  << ast.AppendRule($0, $1) >>
	| Rule << ast.NewRule($0) >>
	;

Rule
	: Root
	| Init
	| Transition
	| IfExpr
	;

Root
	: id "." id "=" id << &ast.Init{Package: ast.IdToString($0), Message: ast.IdToString($2), State: ast.IdToString($4)}, nil >>
	;

Init
	: id "." id "." id "=" id << &ast.Init{Package: ast.IdToString($0), Message: ast.IdToString($2), Field: ast.IdToString($4), State: ast.IdToString($6)}, nil >>
	;

Transition
	: id id "=" id << &ast.Transition{Src: ast.IdToString($0), Input: ast.IdToString($1), Dst: ast.IdToString($3)}, nil >>
	;

IfExpr
	: "if" Expr "then" StateExpr "else" StateExpr << &ast.IfExpr{Condition: $1.(*ast.Expr), Then: $3.(*ast.StateExpr), Else: $5.(*ast.StateExpr)}, nil >>
	;

StateExpr
	: "{" IfExpr "}" << &ast.StateExpr{IfExpr: $1.(*ast.IfExpr)}, nil >>
	| id << &ast.StateExpr{State: ast.IdToString($0)}, nil >>
	;

Function
	: id "(" Params ")" << &ast.Function{Name: ast.IdToString($0), Params: $2.([]*ast.Expr)}, nil >>
	| "(" Expr Comparator Expr ")" << &ast.Function{Name: proto.String($2.(string)), Params: []*ast.Expr{$1.(*ast.Expr), $3.(*ast.Expr)}}, nil >>
	;

Comparator
	: "=="  << "eq", nil >>
	| "<"   << "lt", nil >>
	| "<="  << "le", nil >>
	| ">"   << "gt", nil >>
	| ">="  << "ge", nil >>
	| "&&"  << "and", nil >>
	| "||"  << "or", nil >>
	| "or"
	| "and"
	;

Params
	: Params "," Expr << append($0.([]*ast.Expr), $2.(*ast.Expr)), nil >>
	| Expr << []*ast.Expr{$0.(*ast.Expr)}, nil >>
	;

Expr
	: Terminal << &ast.Expr{Terminal: $0.(*ast.Terminal)}, nil >>
	| Function << &ast.Expr{Function: $0.(*ast.Function)}, nil >>
	;

Terminal
	: Bool << &ast.Terminal{BoolValue: proto.Bool($0.(bool))}, nil >>
	| "int64" "(" int_lit ")" << &ast.Terminal{Int64Value: ast.ToInt64($2)}, nil >>
	| "uint64" "(" int_lit ")" << &ast.Terminal{Uint64Value: ast.ToUint64($2)}, nil >>
	| string_lit << &ast.Terminal{StringValue: ast.ToString($0)}, nil >>
	| id "." id "." id "." "value" << &ast.Terminal{Variable: &ast.Variable{Package: ast.IdToString($0), Message: ast.IdToString($2), Field: ast.IdToString($4), Part: ast.IdToString($6)}}, nil >>
	| id "." id "." id "." "len"  << &ast.Terminal{Variable: &ast.Variable{Package: ast.IdToString($0), Message: ast.IdToString($2), Field: ast.IdToString($4), Part: ast.IdToString($6)}}, nil >>
	;

Bool
	: "true" << true, nil >>
	| "True" << true, nil >>
	| "false" << false, nil >>
	| "False" << false, nil >>
	;






