// Code generated by funcs-gen. DO NOT EDIT.
package funcs

type elemDoubles struct {
	List  Doubles
	Index Int
}

func (this *elemDoubles) Eval() (float64, error) {
	list, err := this.List.Eval()
	if err != nil {
		return 0, err
	}
	index64, err := this.Index.Eval()
	if err != nil {
		return 0, err
	}
	index := int(index64)
	if len(list) == 0 {
		return 0, NewRangeCheckErr(index, len(list))
	}
	if index < 0 {
		index = index % len(list)
	}
	if len(list) <= index {
		return 0, NewRangeCheckErr(index, len(list))
	}
	return list[index], nil
}

func init() {
	Register("elem", new(elemDoubles))
}

//ElemDoubles returns a function that returns the n'th element of the list.
func ElemDoubles(list Doubles, n Int) Double {
	return &elemDoubles{
		List:  list,
		Index: n,
	}
}

type elemInts struct {
	List  Ints
	Index Int
}

func (this *elemInts) Eval() (int64, error) {
	list, err := this.List.Eval()
	if err != nil {
		return 0, err
	}
	index64, err := this.Index.Eval()
	if err != nil {
		return 0, err
	}
	index := int(index64)
	if len(list) == 0 {
		return 0, NewRangeCheckErr(index, len(list))
	}
	if index < 0 {
		index = index % len(list)
	}
	if len(list) <= index {
		return 0, NewRangeCheckErr(index, len(list))
	}
	return list[index], nil
}

func init() {
	Register("elem", new(elemInts))
}

//ElemInts returns a function that returns the n'th element of the list.
func ElemInts(list Ints, n Int) Int {
	return &elemInts{
		List:  list,
		Index: n,
	}
}

type elemUints struct {
	List  Uints
	Index Int
}

func (this *elemUints) Eval() (uint64, error) {
	list, err := this.List.Eval()
	if err != nil {
		return 0, err
	}
	index64, err := this.Index.Eval()
	if err != nil {
		return 0, err
	}
	index := int(index64)
	if len(list) == 0 {
		return 0, NewRangeCheckErr(index, len(list))
	}
	if index < 0 {
		index = index % len(list)
	}
	if len(list) <= index {
		return 0, NewRangeCheckErr(index, len(list))
	}
	return list[index], nil
}

func init() {
	Register("elem", new(elemUints))
}

//ElemUints returns a function that returns the n'th element of the list.
func ElemUints(list Uints, n Int) Uint {
	return &elemUints{
		List:  list,
		Index: n,
	}
}

type elemBools struct {
	List  Bools
	Index Int
}

func (this *elemBools) Eval() (bool, error) {
	list, err := this.List.Eval()
	if err != nil {
		return false, err
	}
	index64, err := this.Index.Eval()
	if err != nil {
		return false, err
	}
	index := int(index64)
	if len(list) == 0 {
		return false, NewRangeCheckErr(index, len(list))
	}
	if index < 0 {
		index = index % len(list)
	}
	if len(list) <= index {
		return false, NewRangeCheckErr(index, len(list))
	}
	return list[index], nil
}

func init() {
	Register("elem", new(elemBools))
}

//ElemBools returns a function that returns the n'th element of the list.
func ElemBools(list Bools, n Int) Bool {
	return &elemBools{
		List:  list,
		Index: n,
	}
}

type elemStrings struct {
	List  Strings
	Index Int
}

func (this *elemStrings) Eval() (string, error) {
	list, err := this.List.Eval()
	if err != nil {
		return "", err
	}
	index64, err := this.Index.Eval()
	if err != nil {
		return "", err
	}
	index := int(index64)
	if len(list) == 0 {
		return "", NewRangeCheckErr(index, len(list))
	}
	if index < 0 {
		index = index % len(list)
	}
	if len(list) <= index {
		return "", NewRangeCheckErr(index, len(list))
	}
	return list[index], nil
}

func init() {
	Register("elem", new(elemStrings))
}

//ElemStrings returns a function that returns the n'th element of the list.
func ElemStrings(list Strings, n Int) String {
	return &elemStrings{
		List:  list,
		Index: n,
	}
}

type elemListOfBytes struct {
	List  ListOfBytes
	Index Int
}

func (this *elemListOfBytes) Eval() ([]byte, error) {
	list, err := this.List.Eval()
	if err != nil {
		return nil, err
	}
	index64, err := this.Index.Eval()
	if err != nil {
		return nil, err
	}
	index := int(index64)
	if len(list) == 0 {
		return nil, NewRangeCheckErr(index, len(list))
	}
	if index < 0 {
		index = index % len(list)
	}
	if len(list) <= index {
		return nil, NewRangeCheckErr(index, len(list))
	}
	return list[index], nil
}

func init() {
	Register("elem", new(elemListOfBytes))
}

//ElemListOfBytes returns a function that returns the n'th element of the list.
func ElemListOfBytes(list ListOfBytes, n Int) Bytes {
	return &elemListOfBytes{
		List:  list,
		Index: n,
	}
}
