// Code generated by protoc-gen-gogo.
// source: msg.proto
// DO NOT EDIT!

/*
Package prototests is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	BigMsg
	SmallMsg
*/
package prototests

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

import strings "strings"
import github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
import sort "sort"
import strconv "strconv"
import reflect "reflect"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// BigMsg contains a field and a message field.
type BigMsg struct {
	Field            *int64    `protobuf:"varint,1,opt,name=Field" json:"Field,omitempty"`
	Msg              *SmallMsg `protobuf:"bytes,3,opt,name=Msg" json:"Msg,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *BigMsg) Reset()         { *m = BigMsg{} }
func (m *BigMsg) String() string { return proto.CompactTextString(m) }
func (*BigMsg) ProtoMessage()    {}

func (m *BigMsg) GetField() int64 {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return 0
}

func (m *BigMsg) GetMsg() *SmallMsg {
	if m != nil {
		return m.Msg
	}
	return nil
}

// SmallMsg only contains some native fields.
type SmallMsg struct {
	ScarBusStop      *string  `protobuf:"bytes,1,opt,name=ScarBusStop" json:"ScarBusStop,omitempty"`
	FlightParachute  []uint32 `protobuf:"fixed32,12,rep,name=FlightParachute" json:"FlightParachute,omitempty"`
	MapShark         *string  `protobuf:"bytes,18,opt,name=MapShark" json:"MapShark,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SmallMsg) Reset()         { *m = SmallMsg{} }
func (m *SmallMsg) String() string { return proto.CompactTextString(m) }
func (*SmallMsg) ProtoMessage()    {}

func (m *SmallMsg) GetScarBusStop() string {
	if m != nil && m.ScarBusStop != nil {
		return *m.ScarBusStop
	}
	return ""
}

func (m *SmallMsg) GetFlightParachute() []uint32 {
	if m != nil {
		return m.FlightParachute
	}
	return nil
}

func (m *SmallMsg) GetMapShark() string {
	if m != nil && m.MapShark != nil {
		return *m.MapShark
	}
	return ""
}

func init() {
	proto.RegisterType((*BigMsg)(nil), "prototests.BigMsg")
	proto.RegisterType((*SmallMsg)(nil), "prototests.SmallMsg")
}
func (this *BigMsg) Description() (desc *descriptor.FileDescriptorSet) {
	return MsgDescription()
}
func (this *SmallMsg) Description() (desc *descriptor.FileDescriptorSet) {
	return MsgDescription()
}
func MsgDescription() (desc *descriptor.FileDescriptorSet) {
	return &descriptor.FileDescriptorSet{File: []*descriptor.FileDescriptorProto{{Name: func(v string) *string { return &v }("google/protobuf/descriptor.proto"),
		Package: func(v string) *string { return &v }("google.protobuf"),
		MessageType: []*descriptor.DescriptorProto{{Name: func(v string) *string { return &v }("FileDescriptorSet"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("file"),
				Number:   func(v int32) *int32 { return &v }(1),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.FileDescriptorProto"),
			}},
		}, {Name: func(v string) *string { return &v }("FileDescriptorProto"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("name"),
				Number: func(v int32) *int32 { return &v }(1),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("package"),
				Number: func(v int32) *int32 { return &v }(2),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("dependency"),
				Number: func(v int32) *int32 { return &v }(3),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("public_dependency"),
				Number: func(v int32) *int32 { return &v }(10),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(5),
			}, {Name: func(v string) *string { return &v }("weak_dependency"),
				Number: func(v int32) *int32 { return &v }(11),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(5),
			}, {Name: func(v string) *string { return &v }("message_type"),
				Number:   func(v int32) *int32 { return &v }(4),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.DescriptorProto"),
			}, {Name: func(v string) *string { return &v }("enum_type"),
				Number:   func(v int32) *int32 { return &v }(5),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.EnumDescriptorProto"),
			}, {Name: func(v string) *string { return &v }("service"),
				Number:   func(v int32) *int32 { return &v }(6),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.ServiceDescriptorProto"),
			}, {Name: func(v string) *string { return &v }("extension"),
				Number:   func(v int32) *int32 { return &v }(7),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.FieldDescriptorProto"),
			}, {Name: func(v string) *string { return &v }("options"),
				Number:   func(v int32) *int32 { return &v }(8),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
			}, {Name: func(v string) *string { return &v }("source_code_info"),
				Number:   func(v int32) *int32 { return &v }(9),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.SourceCodeInfo"),
			}, {Name: func(v string) *string { return &v }("syntax"),
				Number: func(v int32) *int32 { return &v }(12),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}},
		}, {Name: func(v string) *string { return &v }("DescriptorProto"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("name"),
				Number: func(v int32) *int32 { return &v }(1),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("field"),
				Number:   func(v int32) *int32 { return &v }(2),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.FieldDescriptorProto"),
			}, {Name: func(v string) *string { return &v }("extension"),
				Number:   func(v int32) *int32 { return &v }(6),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.FieldDescriptorProto"),
			}, {Name: func(v string) *string { return &v }("nested_type"),
				Number:   func(v int32) *int32 { return &v }(3),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.DescriptorProto"),
			}, {Name: func(v string) *string { return &v }("enum_type"),
				Number:   func(v int32) *int32 { return &v }(4),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.EnumDescriptorProto"),
			}, {Name: func(v string) *string { return &v }("extension_range"),
				Number:   func(v int32) *int32 { return &v }(5),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.DescriptorProto.ExtensionRange"),
			}, {Name: func(v string) *string { return &v }("oneof_decl"),
				Number:   func(v int32) *int32 { return &v }(8),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.OneofDescriptorProto"),
			}, {Name: func(v string) *string { return &v }("options"),
				Number:   func(v int32) *int32 { return &v }(7),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
			}, {Name: func(v string) *string { return &v }("reserved_range"),
				Number:   func(v int32) *int32 { return &v }(9),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.DescriptorProto.ReservedRange"),
			}, {Name: func(v string) *string { return &v }("reserved_name"),
				Number: func(v int32) *int32 { return &v }(10),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}},
			NestedType: []*descriptor.DescriptorProto{{Name: func(v string) *string { return &v }("ExtensionRange"),
				Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("start"),
					Number: func(v int32) *int32 { return &v }(1),
					Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
					Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(5),
				}, {Name: func(v string) *string { return &v }("end"),
					Number: func(v int32) *int32 { return &v }(2),
					Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
					Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(5),
				}},
			}, {Name: func(v string) *string { return &v }("ReservedRange"),
				Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("start"),
					Number: func(v int32) *int32 { return &v }(1),
					Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
					Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(5),
				}, {Name: func(v string) *string { return &v }("end"),
					Number: func(v int32) *int32 { return &v }(2),
					Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
					Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(5),
				}},
			}},
		}, {Name: func(v string) *string { return &v }("FieldDescriptorProto"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("name"),
				Number: func(v int32) *int32 { return &v }(1),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("number"),
				Number: func(v int32) *int32 { return &v }(3),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(5),
			}, {Name: func(v string) *string { return &v }("label"),
				Number:   func(v int32) *int32 { return &v }(4),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(14),
				TypeName: func(v string) *string { return &v }(".google.protobuf.FieldDescriptorProto.Label"),
			}, {Name: func(v string) *string { return &v }("type"),
				Number:   func(v int32) *int32 { return &v }(5),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(14),
				TypeName: func(v string) *string { return &v }(".google.protobuf.FieldDescriptorProto.Type"),
			}, {Name: func(v string) *string { return &v }("type_name"),
				Number: func(v int32) *int32 { return &v }(6),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("extendee"),
				Number: func(v int32) *int32 { return &v }(2),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("default_value"),
				Number: func(v int32) *int32 { return &v }(7),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("oneof_index"),
				Number: func(v int32) *int32 { return &v }(9),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(5),
			}, {Name: func(v string) *string { return &v }("json_name"),
				Number: func(v int32) *int32 { return &v }(10),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("options"),
				Number:   func(v int32) *int32 { return &v }(8),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.FieldOptions"),
			}},
			EnumType: []*descriptor.EnumDescriptorProto{{Name: func(v string) *string { return &v }("Type"),
				Value: []*descriptor.EnumValueDescriptorProto{{Name: func(v string) *string { return &v }("TYPE_DOUBLE"),
					Number: func(v int32) *int32 { return &v }(1),
				}, {Name: func(v string) *string { return &v }("TYPE_FLOAT"),
					Number: func(v int32) *int32 { return &v }(2),
				}, {Name: func(v string) *string { return &v }("TYPE_INT64"),
					Number: func(v int32) *int32 { return &v }(3),
				}, {Name: func(v string) *string { return &v }("TYPE_UINT64"),
					Number: func(v int32) *int32 { return &v }(4),
				}, {Name: func(v string) *string { return &v }("TYPE_INT32"),
					Number: func(v int32) *int32 { return &v }(5),
				}, {Name: func(v string) *string { return &v }("TYPE_FIXED64"),
					Number: func(v int32) *int32 { return &v }(6),
				}, {Name: func(v string) *string { return &v }("TYPE_FIXED32"),
					Number: func(v int32) *int32 { return &v }(7),
				}, {Name: func(v string) *string { return &v }("TYPE_BOOL"),
					Number: func(v int32) *int32 { return &v }(8),
				}, {Name: func(v string) *string { return &v }("TYPE_STRING"),
					Number: func(v int32) *int32 { return &v }(9),
				}, {Name: func(v string) *string { return &v }("TYPE_GROUP"),
					Number: func(v int32) *int32 { return &v }(10),
				}, {Name: func(v string) *string { return &v }("TYPE_MESSAGE"),
					Number: func(v int32) *int32 { return &v }(11),
				}, {Name: func(v string) *string { return &v }("TYPE_BYTES"),
					Number: func(v int32) *int32 { return &v }(12),
				}, {Name: func(v string) *string { return &v }("TYPE_UINT32"),
					Number: func(v int32) *int32 { return &v }(13),
				}, {Name: func(v string) *string { return &v }("TYPE_ENUM"),
					Number: func(v int32) *int32 { return &v }(14),
				}, {Name: func(v string) *string { return &v }("TYPE_SFIXED32"),
					Number: func(v int32) *int32 { return &v }(15),
				}, {Name: func(v string) *string { return &v }("TYPE_SFIXED64"),
					Number: func(v int32) *int32 { return &v }(16),
				}, {Name: func(v string) *string { return &v }("TYPE_SINT32"),
					Number: func(v int32) *int32 { return &v }(17),
				}, {Name: func(v string) *string { return &v }("TYPE_SINT64"),
					Number: func(v int32) *int32 { return &v }(18),
				}},
			}, {Name: func(v string) *string { return &v }("Label"),
				Value: []*descriptor.EnumValueDescriptorProto{{Name: func(v string) *string { return &v }("LABEL_OPTIONAL"),
					Number: func(v int32) *int32 { return &v }(1),
				}, {Name: func(v string) *string { return &v }("LABEL_REQUIRED"),
					Number: func(v int32) *int32 { return &v }(2),
				}, {Name: func(v string) *string { return &v }("LABEL_REPEATED"),
					Number: func(v int32) *int32 { return &v }(3),
				}},
			}},
		}, {Name: func(v string) *string { return &v }("OneofDescriptorProto"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("name"),
				Number: func(v int32) *int32 { return &v }(1),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}},
		}, {Name: func(v string) *string { return &v }("EnumDescriptorProto"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("name"),
				Number: func(v int32) *int32 { return &v }(1),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("value"),
				Number:   func(v int32) *int32 { return &v }(2),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.EnumValueDescriptorProto"),
			}, {Name: func(v string) *string { return &v }("options"),
				Number:   func(v int32) *int32 { return &v }(3),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.EnumOptions"),
			}},
		}, {Name: func(v string) *string { return &v }("EnumValueDescriptorProto"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("name"),
				Number: func(v int32) *int32 { return &v }(1),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("number"),
				Number: func(v int32) *int32 { return &v }(2),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(5),
			}, {Name: func(v string) *string { return &v }("options"),
				Number:   func(v int32) *int32 { return &v }(3),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.EnumValueOptions"),
			}},
		}, {Name: func(v string) *string { return &v }("ServiceDescriptorProto"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("name"),
				Number: func(v int32) *int32 { return &v }(1),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("method"),
				Number:   func(v int32) *int32 { return &v }(2),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.MethodDescriptorProto"),
			}, {Name: func(v string) *string { return &v }("options"),
				Number:   func(v int32) *int32 { return &v }(3),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.ServiceOptions"),
			}},
		}, {Name: func(v string) *string { return &v }("MethodDescriptorProto"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("name"),
				Number: func(v int32) *int32 { return &v }(1),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("input_type"),
				Number: func(v int32) *int32 { return &v }(2),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("output_type"),
				Number: func(v int32) *int32 { return &v }(3),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("options"),
				Number:   func(v int32) *int32 { return &v }(4),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.MethodOptions"),
			}, {Name: func(v string) *string { return &v }("client_streaming"),
				Number:       func(v int32) *int32 { return &v }(5),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("server_streaming"),
				Number:       func(v int32) *int32 { return &v }(6),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}},
		}, {Name: func(v string) *string { return &v }("FileOptions"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("java_package"),
				Number: func(v int32) *int32 { return &v }(1),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("java_outer_classname"),
				Number: func(v int32) *int32 { return &v }(8),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("java_multiple_files"),
				Number:       func(v int32) *int32 { return &v }(10),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("java_generate_equals_and_hash"),
				Number:       func(v int32) *int32 { return &v }(20),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("java_string_check_utf8"),
				Number:       func(v int32) *int32 { return &v }(27),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("optimize_for"),
				Number:       func(v int32) *int32 { return &v }(9),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(14),
				TypeName:     func(v string) *string { return &v }(".google.protobuf.FileOptions.OptimizeMode"),
				DefaultValue: func(v string) *string { return &v }("SPEED"),
			}, {Name: func(v string) *string { return &v }("go_package"),
				Number: func(v int32) *int32 { return &v }(11),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("cc_generic_services"),
				Number:       func(v int32) *int32 { return &v }(16),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("java_generic_services"),
				Number:       func(v int32) *int32 { return &v }(17),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("py_generic_services"),
				Number:       func(v int32) *int32 { return &v }(18),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("deprecated"),
				Number:       func(v int32) *int32 { return &v }(23),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("cc_enable_arenas"),
				Number:       func(v int32) *int32 { return &v }(31),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("objc_class_prefix"),
				Number: func(v int32) *int32 { return &v }(36),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("csharp_namespace"),
				Number: func(v int32) *int32 { return &v }(37),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("javanano_use_deprecated_package"),
				Number: func(v int32) *int32 { return &v }(38),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			}, {Name: func(v string) *string { return &v }("uninterpreted_option"),
				Number:   func(v int32) *int32 { return &v }(999),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.UninterpretedOption"),
			}},
			EnumType: []*descriptor.EnumDescriptorProto{{Name: func(v string) *string { return &v }("OptimizeMode"),
				Value: []*descriptor.EnumValueDescriptorProto{{Name: func(v string) *string { return &v }("SPEED"),
					Number: func(v int32) *int32 { return &v }(1),
				}, {Name: func(v string) *string { return &v }("CODE_SIZE"),
					Number: func(v int32) *int32 { return &v }(2),
				}, {Name: func(v string) *string { return &v }("LITE_RUNTIME"),
					Number: func(v int32) *int32 { return &v }(3),
				}},
			}},
			ExtensionRange: []*descriptor.DescriptorProto_ExtensionRange{{Start: func(v int32) *int32 { return &v }(1000),
				End: func(v int32) *int32 { return &v }(536870912),
			}},
		}, {Name: func(v string) *string { return &v }("MessageOptions"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("message_set_wire_format"),
				Number:       func(v int32) *int32 { return &v }(1),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("no_standard_descriptor_accessor"),
				Number:       func(v int32) *int32 { return &v }(2),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("deprecated"),
				Number:       func(v int32) *int32 { return &v }(3),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("map_entry"),
				Number: func(v int32) *int32 { return &v }(7),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			}, {Name: func(v string) *string { return &v }("uninterpreted_option"),
				Number:   func(v int32) *int32 { return &v }(999),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.UninterpretedOption"),
			}},
			ExtensionRange: []*descriptor.DescriptorProto_ExtensionRange{{Start: func(v int32) *int32 { return &v }(1000),
				End: func(v int32) *int32 { return &v }(536870912),
			}},
		}, {Name: func(v string) *string { return &v }("FieldOptions"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("ctype"),
				Number:       func(v int32) *int32 { return &v }(1),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(14),
				TypeName:     func(v string) *string { return &v }(".google.protobuf.FieldOptions.CType"),
				DefaultValue: func(v string) *string { return &v }("STRING"),
			}, {Name: func(v string) *string { return &v }("packed"),
				Number: func(v int32) *int32 { return &v }(2),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			}, {Name: func(v string) *string { return &v }("jstype"),
				Number:       func(v int32) *int32 { return &v }(6),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(14),
				TypeName:     func(v string) *string { return &v }(".google.protobuf.FieldOptions.JSType"),
				DefaultValue: func(v string) *string { return &v }("JS_NORMAL"),
			}, {Name: func(v string) *string { return &v }("lazy"),
				Number:       func(v int32) *int32 { return &v }(5),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("deprecated"),
				Number:       func(v int32) *int32 { return &v }(3),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("weak"),
				Number:       func(v int32) *int32 { return &v }(10),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("uninterpreted_option"),
				Number:   func(v int32) *int32 { return &v }(999),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.UninterpretedOption"),
			}},
			EnumType: []*descriptor.EnumDescriptorProto{{Name: func(v string) *string { return &v }("CType"),
				Value: []*descriptor.EnumValueDescriptorProto{{Name: func(v string) *string { return &v }("STRING"),
					Number: func(v int32) *int32 { return &v }(0),
				}, {Name: func(v string) *string { return &v }("CORD"),
					Number: func(v int32) *int32 { return &v }(1),
				}, {Name: func(v string) *string { return &v }("STRING_PIECE"),
					Number: func(v int32) *int32 { return &v }(2),
				}},
			}, {Name: func(v string) *string { return &v }("JSType"),
				Value: []*descriptor.EnumValueDescriptorProto{{Name: func(v string) *string { return &v }("JS_NORMAL"),
					Number: func(v int32) *int32 { return &v }(0),
				}, {Name: func(v string) *string { return &v }("JS_STRING"),
					Number: func(v int32) *int32 { return &v }(1),
				}, {Name: func(v string) *string { return &v }("JS_NUMBER"),
					Number: func(v int32) *int32 { return &v }(2),
				}},
			}},
			ExtensionRange: []*descriptor.DescriptorProto_ExtensionRange{{Start: func(v int32) *int32 { return &v }(1000),
				End: func(v int32) *int32 { return &v }(536870912),
			}},
		}, {Name: func(v string) *string { return &v }("EnumOptions"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("allow_alias"),
				Number: func(v int32) *int32 { return &v }(2),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			}, {Name: func(v string) *string { return &v }("deprecated"),
				Number:       func(v int32) *int32 { return &v }(3),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("uninterpreted_option"),
				Number:   func(v int32) *int32 { return &v }(999),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.UninterpretedOption"),
			}},
			ExtensionRange: []*descriptor.DescriptorProto_ExtensionRange{{Start: func(v int32) *int32 { return &v }(1000),
				End: func(v int32) *int32 { return &v }(536870912),
			}},
		}, {Name: func(v string) *string { return &v }("EnumValueOptions"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("deprecated"),
				Number:       func(v int32) *int32 { return &v }(1),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("uninterpreted_option"),
				Number:   func(v int32) *int32 { return &v }(999),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.UninterpretedOption"),
			}},
			ExtensionRange: []*descriptor.DescriptorProto_ExtensionRange{{Start: func(v int32) *int32 { return &v }(1000),
				End: func(v int32) *int32 { return &v }(536870912),
			}},
		}, {Name: func(v string) *string { return &v }("ServiceOptions"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("deprecated"),
				Number:       func(v int32) *int32 { return &v }(33),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("uninterpreted_option"),
				Number:   func(v int32) *int32 { return &v }(999),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.UninterpretedOption"),
			}},
			ExtensionRange: []*descriptor.DescriptorProto_ExtensionRange{{Start: func(v int32) *int32 { return &v }(1000),
				End: func(v int32) *int32 { return &v }(536870912),
			}},
		}, {Name: func(v string) *string { return &v }("MethodOptions"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("deprecated"),
				Number:       func(v int32) *int32 { return &v }(33),
				Label:        func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:         func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				DefaultValue: func(v string) *string { return &v }("false"),
			}, {Name: func(v string) *string { return &v }("uninterpreted_option"),
				Number:   func(v int32) *int32 { return &v }(999),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.UninterpretedOption"),
			}},
			ExtensionRange: []*descriptor.DescriptorProto_ExtensionRange{{Start: func(v int32) *int32 { return &v }(1000),
				End: func(v int32) *int32 { return &v }(536870912),
			}},
		}, {Name: func(v string) *string { return &v }("UninterpretedOption"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("name"),
				Number:   func(v int32) *int32 { return &v }(2),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.UninterpretedOption.NamePart"),
			}, {Name: func(v string) *string { return &v }("identifier_value"),
				Number: func(v int32) *int32 { return &v }(3),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("positive_int_value"),
				Number: func(v int32) *int32 { return &v }(4),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(4),
			}, {Name: func(v string) *string { return &v }("negative_int_value"),
				Number: func(v int32) *int32 { return &v }(5),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(3),
			}, {Name: func(v string) *string { return &v }("double_value"),
				Number: func(v int32) *int32 { return &v }(6),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(1),
			}, {Name: func(v string) *string { return &v }("string_value"),
				Number: func(v int32) *int32 { return &v }(7),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(12),
			}, {Name: func(v string) *string { return &v }("aggregate_value"),
				Number: func(v int32) *int32 { return &v }(8),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}},
			NestedType: []*descriptor.DescriptorProto{{Name: func(v string) *string { return &v }("NamePart"),
				Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("name_part"),
					Number: func(v int32) *int32 { return &v }(1),
					Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(2),
					Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
				}, {Name: func(v string) *string { return &v }("is_extension"),
					Number: func(v int32) *int32 { return &v }(2),
					Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(2),
					Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
				}},
			}},
		}, {Name: func(v string) *string { return &v }("SourceCodeInfo"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("location"),
				Number:   func(v int32) *int32 { return &v }(1),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".google.protobuf.SourceCodeInfo.Location"),
			}},
			NestedType: []*descriptor.DescriptorProto{{Name: func(v string) *string { return &v }("Location"),
				Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("path"),
					Number: func(v int32) *int32 { return &v }(1),
					Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
					Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(5),
					Options: &descriptor.FieldOptions{Packed: func(v bool) *bool { return &v }(true),
						XXX_extensions: map[int32]proto.Extension{},
					},
				}, {Name: func(v string) *string { return &v }("span"),
					Number: func(v int32) *int32 { return &v }(2),
					Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
					Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(5),
					Options: &descriptor.FieldOptions{Packed: func(v bool) *bool { return &v }(true),
						XXX_extensions: map[int32]proto.Extension{},
					},
				}, {Name: func(v string) *string { return &v }("leading_comments"),
					Number: func(v int32) *int32 { return &v }(3),
					Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
					Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
				}, {Name: func(v string) *string { return &v }("trailing_comments"),
					Number: func(v int32) *int32 { return &v }(4),
					Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
					Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
				}, {Name: func(v string) *string { return &v }("leading_detached_comments"),
					Number: func(v int32) *int32 { return &v }(6),
					Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
					Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
				}},
			}},
		}},
		Options: &descriptor.FileOptions{JavaPackage: func(v string) *string { return &v }("com.google.protobuf"),
			JavaOuterClassname: func(v string) *string { return &v }("DescriptorProtos"),
			OptimizeFor:        func(v descriptor.FileOptions_OptimizeMode) *descriptor.FileOptions_OptimizeMode { return &v }(1),
			GoPackage:          func(v string) *string { return &v }("descriptor"),
			ObjcClassPrefix:    func(v string) *string { return &v }("GPB"),
			CsharpNamespace:    func(v string) *string { return &v }("Google.Protobuf.Reflection"),
			XXX_extensions:     map[int32]proto.Extension{},
		},
	}, {Name: func(v string) *string { return &v }("github.com/gogo/protobuf/gogoproto/gogo.proto"),
		Package:    func(v string) *string { return &v }("gogoproto"),
		Dependency: []string{"google/protobuf/descriptor.proto"},
		Extension: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("goproto_enum_prefix"),
			Number:   func(v int32) *int32 { return &v }(62001),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.EnumOptions"),
		}, {Name: func(v string) *string { return &v }("goproto_enum_stringer"),
			Number:   func(v int32) *int32 { return &v }(62021),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.EnumOptions"),
		}, {Name: func(v string) *string { return &v }("enum_stringer"),
			Number:   func(v int32) *int32 { return &v }(62022),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.EnumOptions"),
		}, {Name: func(v string) *string { return &v }("goproto_getters_all"),
			Number:   func(v int32) *int32 { return &v }(63001),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("goproto_enum_prefix_all"),
			Number:   func(v int32) *int32 { return &v }(63002),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("goproto_stringer_all"),
			Number:   func(v int32) *int32 { return &v }(63003),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("verbose_equal_all"),
			Number:   func(v int32) *int32 { return &v }(63004),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("face_all"),
			Number:   func(v int32) *int32 { return &v }(63005),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("gostring_all"),
			Number:   func(v int32) *int32 { return &v }(63006),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("populate_all"),
			Number:   func(v int32) *int32 { return &v }(63007),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("stringer_all"),
			Number:   func(v int32) *int32 { return &v }(63008),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("onlyone_all"),
			Number:   func(v int32) *int32 { return &v }(63009),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("equal_all"),
			Number:   func(v int32) *int32 { return &v }(63013),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("description_all"),
			Number:   func(v int32) *int32 { return &v }(63014),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("testgen_all"),
			Number:   func(v int32) *int32 { return &v }(63015),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("benchgen_all"),
			Number:   func(v int32) *int32 { return &v }(63016),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("marshaler_all"),
			Number:   func(v int32) *int32 { return &v }(63017),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("unmarshaler_all"),
			Number:   func(v int32) *int32 { return &v }(63018),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("sizer_all"),
			Number:   func(v int32) *int32 { return &v }(63020),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("goproto_enum_stringer_all"),
			Number:   func(v int32) *int32 { return &v }(63021),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("enum_stringer_all"),
			Number:   func(v int32) *int32 { return &v }(63022),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("unsafe_marshaler_all"),
			Number:   func(v int32) *int32 { return &v }(63023),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("unsafe_unmarshaler_all"),
			Number:   func(v int32) *int32 { return &v }(63024),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("goproto_extensions_map_all"),
			Number:   func(v int32) *int32 { return &v }(63025),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("goproto_unrecognized_all"),
			Number:   func(v int32) *int32 { return &v }(63026),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("gogoproto_import"),
			Number:   func(v int32) *int32 { return &v }(63027),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FileOptions"),
		}, {Name: func(v string) *string { return &v }("goproto_getters"),
			Number:   func(v int32) *int32 { return &v }(64001),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("goproto_stringer"),
			Number:   func(v int32) *int32 { return &v }(64003),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("verbose_equal"),
			Number:   func(v int32) *int32 { return &v }(64004),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("face"),
			Number:   func(v int32) *int32 { return &v }(64005),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("gostring"),
			Number:   func(v int32) *int32 { return &v }(64006),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("populate"),
			Number:   func(v int32) *int32 { return &v }(64007),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("stringer"),
			Number:   func(v int32) *int32 { return &v }(67008),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("onlyone"),
			Number:   func(v int32) *int32 { return &v }(64009),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("equal"),
			Number:   func(v int32) *int32 { return &v }(64013),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("description"),
			Number:   func(v int32) *int32 { return &v }(64014),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("testgen"),
			Number:   func(v int32) *int32 { return &v }(64015),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("benchgen"),
			Number:   func(v int32) *int32 { return &v }(64016),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("marshaler"),
			Number:   func(v int32) *int32 { return &v }(64017),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("unmarshaler"),
			Number:   func(v int32) *int32 { return &v }(64018),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("sizer"),
			Number:   func(v int32) *int32 { return &v }(64020),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("unsafe_marshaler"),
			Number:   func(v int32) *int32 { return &v }(64023),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("unsafe_unmarshaler"),
			Number:   func(v int32) *int32 { return &v }(64024),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("goproto_extensions_map"),
			Number:   func(v int32) *int32 { return &v }(64025),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("goproto_unrecognized"),
			Number:   func(v int32) *int32 { return &v }(64026),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.MessageOptions"),
		}, {Name: func(v string) *string { return &v }("nullable"),
			Number:   func(v int32) *int32 { return &v }(65001),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FieldOptions"),
		}, {Name: func(v string) *string { return &v }("embed"),
			Number:   func(v int32) *int32 { return &v }(65002),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(8),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FieldOptions"),
		}, {Name: func(v string) *string { return &v }("customtype"),
			Number:   func(v int32) *int32 { return &v }(65003),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FieldOptions"),
		}, {Name: func(v string) *string { return &v }("customname"),
			Number:   func(v int32) *int32 { return &v }(65004),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FieldOptions"),
		}, {Name: func(v string) *string { return &v }("jsontag"),
			Number:   func(v int32) *int32 { return &v }(65005),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FieldOptions"),
		}, {Name: func(v string) *string { return &v }("moretags"),
			Number:   func(v int32) *int32 { return &v }(65006),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FieldOptions"),
		}, {Name: func(v string) *string { return &v }("casttype"),
			Number:   func(v int32) *int32 { return &v }(65007),
			Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
			Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			Extendee: func(v string) *string { return &v }(".google.protobuf.FieldOptions"),
		}},
		Options: &descriptor.FileOptions{JavaPackage: func(v string) *string { return &v }("com.google.protobuf"),
			JavaOuterClassname: func(v string) *string { return &v }("GoGoProtos"),
			XXX_extensions:     map[int32]proto.Extension{},
		},
	}, {Name: func(v string) *string { return &v }("msg.proto"),
		Package:    func(v string) *string { return &v }("prototests"),
		Dependency: []string{"github.com/gogo/protobuf/gogoproto/gogo.proto"},
		MessageType: []*descriptor.DescriptorProto{{Name: func(v string) *string { return &v }("BigMsg"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("Field"),
				Number: func(v int32) *int32 { return &v }(1),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(3),
			}, {Name: func(v string) *string { return &v }("Msg"),
				Number:   func(v int32) *int32 { return &v }(3),
				Label:    func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:     func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(11),
				TypeName: func(v string) *string { return &v }(".prototests.SmallMsg"),
			}},
		}, {Name: func(v string) *string { return &v }("SmallMsg"),
			Field: []*descriptor.FieldDescriptorProto{{Name: func(v string) *string { return &v }("ScarBusStop"),
				Number: func(v int32) *int32 { return &v }(1),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}, {Name: func(v string) *string { return &v }("FlightParachute"),
				Number: func(v int32) *int32 { return &v }(12),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(3),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(7),
			}, {Name: func(v string) *string { return &v }("MapShark"),
				Number: func(v int32) *int32 { return &v }(18),
				Label:  func(v descriptor.FieldDescriptorProto_Label) *descriptor.FieldDescriptorProto_Label { return &v }(1),
				Type:   func(v descriptor.FieldDescriptorProto_Type) *descriptor.FieldDescriptorProto_Type { return &v }(9),
			}},
		}},
		Options: &descriptor.FileOptions{XXX_extensions: map[int32]proto.Extension{63006: proto.NewExtension([]byte{0xf0, 0xe1, 0x1e, 0x1}), 63007: proto.NewExtension([]byte{0xf8, 0xe1, 0x1e, 0x1}), 63014: proto.NewExtension([]byte{0xb0, 0xe2, 0x1e, 0x1})}},
	}},
	}
}
func (this *BigMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&prototests.BigMsg{")
	if this.Field != nil {
		s = append(s, "Field: "+valueToGoStringMsg(this.Field, "int64")+",\n")
	}
	if this.Msg != nil {
		s = append(s, "Msg: "+fmt.Sprintf("%#v", this.Msg)+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SmallMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&prototests.SmallMsg{")
	if this.ScarBusStop != nil {
		s = append(s, "ScarBusStop: "+valueToGoStringMsg(this.ScarBusStop, "string")+",\n")
	}
	if this.FlightParachute != nil {
		s = append(s, "FlightParachute: "+fmt.Sprintf("%#v", this.FlightParachute)+",\n")
	}
	if this.MapShark != nil {
		s = append(s, "MapShark: "+valueToGoStringMsg(this.MapShark, "string")+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringMsg(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func extensionToGoStringMsg(e map[int32]github_com_gogo_protobuf_proto.Extension) string {
	if e == nil {
		return "nil"
	}
	s := "map[int32]proto.Extension{"
	keys := make([]int, 0, len(e))
	for k := range e {
		keys = append(keys, int(k))
	}
	sort.Ints(keys)
	ss := []string{}
	for _, k := range keys {
		ss = append(ss, strconv.Itoa(k)+": "+e[int32(k)].GoString())
	}
	s += strings.Join(ss, ",") + "}"
	return s
}
func NewPopulatedBigMsg(r randyMsg, easy bool) *BigMsg {
	this := &BigMsg{}
	if r.Intn(10) != 0 {
		v1 := int64(r.Int63())
		if r.Intn(2) == 0 {
			v1 *= -1
		}
		this.Field = &v1
	}
	if r.Intn(10) != 0 {
		this.Msg = NewPopulatedSmallMsg(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMsg(r, 4)
	}
	return this
}

func NewPopulatedSmallMsg(r randyMsg, easy bool) *SmallMsg {
	this := &SmallMsg{}
	if r.Intn(10) != 0 {
		v2 := randStringMsg(r)
		this.ScarBusStop = &v2
	}
	if r.Intn(10) != 0 {
		v3 := r.Intn(100)
		this.FlightParachute = make([]uint32, v3)
		for i := 0; i < v3; i++ {
			this.FlightParachute[i] = uint32(r.Uint32())
		}
	}
	if r.Intn(10) != 0 {
		v4 := randStringMsg(r)
		this.MapShark = &v4
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedMsg(r, 19)
	}
	return this
}

type randyMsg interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneMsg(r randyMsg) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringMsg(r randyMsg) string {
	v5 := r.Intn(100)
	tmps := make([]rune, v5)
	for i := 0; i < v5; i++ {
		tmps[i] = randUTF8RuneMsg(r)
	}
	return string(tmps)
}
func randUnrecognizedMsg(r randyMsg, maxFieldNumber int) (data []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		data = randFieldMsg(data, r, fieldNumber, wire)
	}
	return data
}
func randFieldMsg(data []byte, r randyMsg, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		data = encodeVarintPopulateMsg(data, uint64(key))
		v6 := r.Int63()
		if r.Intn(2) == 0 {
			v6 *= -1
		}
		data = encodeVarintPopulateMsg(data, uint64(v6))
	case 1:
		data = encodeVarintPopulateMsg(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		data = encodeVarintPopulateMsg(data, uint64(key))
		ll := r.Intn(100)
		data = encodeVarintPopulateMsg(data, uint64(ll))
		for j := 0; j < ll; j++ {
			data = append(data, byte(r.Intn(256)))
		}
	default:
		data = encodeVarintPopulateMsg(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return data
}
func encodeVarintPopulateMsg(data []byte, v uint64) []byte {
	for v >= 1<<7 {
		data = append(data, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	data = append(data, uint8(v))
	return data
}
