// Code generated by protoc-gen-gogo.
// source: typewriterprison.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	typewriterprison.proto

It has these top-level messages:
	TypewriterPrison
	PocketRoses
*/
package main

import proto "github.com/gogo/protobuf/proto"
import math "math"

// discarding unused import gogoproto "github.com/gogo/protobuf/gogoproto/gogo.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type DivorceFair int32

const (
	DivorceFair_Lawyer    DivorceFair = 4
	DivorceFair_OldMan    DivorceFair = 5
	DivorceFair_Help      DivorceFair = 6
	DivorceFair_Radar     DivorceFair = 9
	DivorceFair_Arm       DivorceFair = 10
	DivorceFair_Verse     DivorceFair = 11
	DivorceFair_Nuts      DivorceFair = 15
	DivorceFair_Briefcase DivorceFair = 21
	DivorceFair_Palace    DivorceFair = 22
)

var DivorceFair_name = map[int32]string{
	4:  "Lawyer",
	5:  "OldMan",
	6:  "Help",
	9:  "Radar",
	10: "Arm",
	11: "Verse",
	15: "Nuts",
	21: "Briefcase",
	22: "Palace",
}
var DivorceFair_value = map[string]int32{
	"Lawyer":    4,
	"OldMan":    5,
	"Help":      6,
	"Radar":     9,
	"Arm":       10,
	"Verse":     11,
	"Nuts":      15,
	"Briefcase": 21,
	"Palace":    22,
}

func (x DivorceFair) Enum() *DivorceFair {
	p := new(DivorceFair)
	*p = x
	return p
}
func (x DivorceFair) String() string {
	return proto.EnumName(DivorceFair_name, int32(x))
}
func (x *DivorceFair) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DivorceFair_value, data, "DivorceFair")
	if err != nil {
		return err
	}
	*x = DivorceFair(value)
	return nil
}

type HopeArch int32

const (
	HopeArch_Mind        HopeArch = 0
	HopeArch_Kennel      HopeArch = 1
	HopeArch_Corn        HopeArch = 2
	HopeArch_Silence     HopeArch = 3
	HopeArch_Lobster     HopeArch = 4
	HopeArch_Oven        HopeArch = 5
	HopeArch_Nose        HopeArch = 6
	HopeArch_Navel       HopeArch = 7
	HopeArch_Pill        HopeArch = 8
	HopeArch_Holly       HopeArch = 9
	HopeArch_Doctrine    HopeArch = 10
	HopeArch_Fork        HopeArch = 11
	HopeArch_Belt        HopeArch = 12
	HopeArch_Cult        HopeArch = 13
	HopeArch_Tusk        HopeArch = 14
	HopeArch_Chips       HopeArch = 15
	HopeArch_Tent        HopeArch = 16
	HopeArch_Coat        HopeArch = 17
	HopeArch_Court       HopeArch = 18
	HopeArch_Runaway     HopeArch = 19
	HopeArch_Mulberry    HopeArch = 20
	HopeArch_Politician  HopeArch = 21
	HopeArch_Message     HopeArch = 22
	HopeArch_Teacher     HopeArch = 23
	HopeArch_Lift        HopeArch = 24
	HopeArch_Danger      HopeArch = 25
	HopeArch_Order       HopeArch = 26
	HopeArch_Title       HopeArch = 27
	HopeArch_Wheelbarrow HopeArch = 28
	HopeArch_Hosepipe    HopeArch = 29
	HopeArch_Carpenter   HopeArch = 30
	HopeArch_Shop        HopeArch = 31
	HopeArch_Nile        HopeArch = 32
	HopeArch_Cloud       HopeArch = 33
	HopeArch_Mill        HopeArch = 34
	HopeArch_Wallet      HopeArch = 35
	HopeArch_Sugar       HopeArch = 36
	HopeArch_Crisis      HopeArch = 37
	HopeArch_Duty        HopeArch = 38
	HopeArch_Milkshake   HopeArch = 39
	HopeArch_Tap         HopeArch = 40
	HopeArch_Clay        HopeArch = 41
	HopeArch_Coronet     HopeArch = 42
	HopeArch_Breakfast   HopeArch = 43
	HopeArch_File        HopeArch = 44
	HopeArch_Bulldozer   HopeArch = 45
	HopeArch_Mattress    HopeArch = 46
	HopeArch_Minute      HopeArch = 47
	HopeArch_Chisel      HopeArch = 48
	HopeArch_Aspirin     HopeArch = 49
	HopeArch_Roulette    HopeArch = 50
	HopeArch_Ham         HopeArch = 51
	HopeArch_Bench       HopeArch = 52
	HopeArch_Miner       HopeArch = 53
)

var HopeArch_name = map[int32]string{
	0:  "Mind",
	1:  "Kennel",
	2:  "Corn",
	3:  "Silence",
	4:  "Lobster",
	5:  "Oven",
	6:  "Nose",
	7:  "Navel",
	8:  "Pill",
	9:  "Holly",
	10: "Doctrine",
	11: "Fork",
	12: "Belt",
	13: "Cult",
	14: "Tusk",
	15: "Chips",
	16: "Tent",
	17: "Coat",
	18: "Court",
	19: "Runaway",
	20: "Mulberry",
	21: "Politician",
	22: "Message",
	23: "Teacher",
	24: "Lift",
	25: "Danger",
	26: "Order",
	27: "Title",
	28: "Wheelbarrow",
	29: "Hosepipe",
	30: "Carpenter",
	31: "Shop",
	32: "Nile",
	33: "Cloud",
	34: "Mill",
	35: "Wallet",
	36: "Sugar",
	37: "Crisis",
	38: "Duty",
	39: "Milkshake",
	40: "Tap",
	41: "Clay",
	42: "Coronet",
	43: "Breakfast",
	44: "File",
	45: "Bulldozer",
	46: "Mattress",
	47: "Minute",
	48: "Chisel",
	49: "Aspirin",
	50: "Roulette",
	51: "Ham",
	52: "Bench",
	53: "Miner",
}
var HopeArch_value = map[string]int32{
	"Mind":        0,
	"Kennel":      1,
	"Corn":        2,
	"Silence":     3,
	"Lobster":     4,
	"Oven":        5,
	"Nose":        6,
	"Navel":       7,
	"Pill":        8,
	"Holly":       9,
	"Doctrine":    10,
	"Fork":        11,
	"Belt":        12,
	"Cult":        13,
	"Tusk":        14,
	"Chips":       15,
	"Tent":        16,
	"Coat":        17,
	"Court":       18,
	"Runaway":     19,
	"Mulberry":    20,
	"Politician":  21,
	"Message":     22,
	"Teacher":     23,
	"Lift":        24,
	"Danger":      25,
	"Order":       26,
	"Title":       27,
	"Wheelbarrow": 28,
	"Hosepipe":    29,
	"Carpenter":   30,
	"Shop":        31,
	"Nile":        32,
	"Cloud":       33,
	"Mill":        34,
	"Wallet":      35,
	"Sugar":       36,
	"Crisis":      37,
	"Duty":        38,
	"Milkshake":   39,
	"Tap":         40,
	"Clay":        41,
	"Coronet":     42,
	"Breakfast":   43,
	"File":        44,
	"Bulldozer":   45,
	"Mattress":    46,
	"Minute":      47,
	"Chisel":      48,
	"Aspirin":     49,
	"Roulette":    50,
	"Ham":         51,
	"Bench":       52,
	"Miner":       53,
}

func (x HopeArch) Enum() *HopeArch {
	p := new(HopeArch)
	*p = x
	return p
}
func (x HopeArch) String() string {
	return proto.EnumName(HopeArch_name, int32(x))
}
func (x *HopeArch) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HopeArch_value, data, "HopeArch")
	if err != nil {
		return err
	}
	*x = HopeArch(value)
	return nil
}

type BullySunrise int32

const (
	BullySunrise_Sandals  BullySunrise = 0
	BullySunrise_Showcase BullySunrise = 1
	BullySunrise_Florist  BullySunrise = 2
	BullySunrise_Fridge   BullySunrise = 3
	BullySunrise_Tram     BullySunrise = 4
	BullySunrise_Porch    BullySunrise = 5
	BullySunrise_Skylight BullySunrise = 6
	BullySunrise_Joke     BullySunrise = 7
	BullySunrise_Leather  BullySunrise = 8
	BullySunrise_Crane    BullySunrise = 9
	BullySunrise_Tour     BullySunrise = 10
)

var BullySunrise_name = map[int32]string{
	0:  "Sandals",
	1:  "Showcase",
	2:  "Florist",
	3:  "Fridge",
	4:  "Tram",
	5:  "Porch",
	6:  "Skylight",
	7:  "Joke",
	8:  "Leather",
	9:  "Crane",
	10: "Tour",
}
var BullySunrise_value = map[string]int32{
	"Sandals":  0,
	"Showcase": 1,
	"Florist":  2,
	"Fridge":   3,
	"Tram":     4,
	"Porch":    5,
	"Skylight": 6,
	"Joke":     7,
	"Leather":  8,
	"Crane":    9,
	"Tour":     10,
}

func (x BullySunrise) Enum() *BullySunrise {
	p := new(BullySunrise)
	*p = x
	return p
}
func (x BullySunrise) String() string {
	return proto.EnumName(BullySunrise_name, int32(x))
}
func (x *BullySunrise) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BullySunrise_value, data, "BullySunrise")
	if err != nil {
		return err
	}
	*x = BullySunrise(value)
	return nil
}

type TypewriterPrison struct {
	WineMessenger    []byte       `protobuf:"bytes,1,opt" json:"WineMessenger,omitempty"`
	ShoelaceBeer     []byte       `protobuf:"bytes,2,opt" json:"ShoelaceBeer,omitempty"`
	PocketRoses      *PocketRoses `protobuf:"bytes,3,opt" json:"PocketRoses,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *TypewriterPrison) Reset()         { *m = TypewriterPrison{} }
func (m *TypewriterPrison) String() string { return proto.CompactTextString(m) }
func (*TypewriterPrison) ProtoMessage()    {}

func (m *TypewriterPrison) GetWineMessenger() []byte {
	if m != nil {
		return m.WineMessenger
	}
	return nil
}

func (m *TypewriterPrison) GetShoelaceBeer() []byte {
	if m != nil {
		return m.ShoelaceBeer
	}
	return nil
}

func (m *TypewriterPrison) GetPocketRoses() *PocketRoses {
	if m != nil {
		return m.PocketRoses
	}
	return nil
}

type PocketRoses struct {
	ScarBusStop      *string       `protobuf:"bytes,1,opt" json:"ScarBusStop,omitempty"`
	BadgeShopping    *int64        `protobuf:"varint,2,opt" json:"BadgeShopping,omitempty"`
	DaisySled        *int64        `protobuf:"varint,3,opt" json:"DaisySled,omitempty"`
	SubmarineSaw     *int64        `protobuf:"varint,4,opt" json:"SubmarineSaw,omitempty"`
	SmileLetter      *bool         `protobuf:"varint,5,opt" json:"SmileLetter,omitempty"`
	IconHope         *BullySunrise `protobuf:"varint,6,opt,enum=main.BullySunrise" json:"IconHope,omitempty"`
	VanPurse         *HopeArch     `protobuf:"varint,7,opt,enum=main.HopeArch" json:"VanPurse,omitempty"`
	MenuPaperclip    []string      `protobuf:"bytes,8,rep" json:"MenuPaperclip,omitempty"`
	BeetlePoker      []string      `protobuf:"bytes,9,rep" json:"BeetlePoker,omitempty"`
	WigPride         []string      `protobuf:"bytes,10,rep" json:"WigPride,omitempty"`
	DivorceFair      *DivorceFair  `protobuf:"varint,11,opt,enum=main.DivorceFair" json:"DivorceFair,omitempty"`
	FlightParachute  []uint32      `protobuf:"fixed32,12,rep" json:"FlightParachute,omitempty"`
	BeerRace         []uint32      `protobuf:"fixed32,13,rep" json:"BeerRace,omitempty"`
	LoftQuarry       [][]byte      `protobuf:"bytes,14,rep" json:"LoftQuarry,omitempty"`
	TaxiDivorce      [][]byte      `protobuf:"bytes,15,rep" json:"TaxiDivorce,omitempty"`
	ElectionButter   []uint32      `protobuf:"fixed32,16,rep" json:"ElectionButter,omitempty"`
	BriefcaseBaboon  [][]byte      `protobuf:"bytes,17,rep" json:"BriefcaseBaboon,omitempty"`
	MapShark         *string       `protobuf:"bytes,18,opt" json:"MapShark,omitempty"`
	NetInterlude     *bool         `protobuf:"varint,19,opt" json:"NetInterlude,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PocketRoses) Reset()         { *m = PocketRoses{} }
func (m *PocketRoses) String() string { return proto.CompactTextString(m) }
func (*PocketRoses) ProtoMessage()    {}

func (m *PocketRoses) GetScarBusStop() string {
	if m != nil && m.ScarBusStop != nil {
		return *m.ScarBusStop
	}
	return ""
}

func (m *PocketRoses) GetBadgeShopping() int64 {
	if m != nil && m.BadgeShopping != nil {
		return *m.BadgeShopping
	}
	return 0
}

func (m *PocketRoses) GetDaisySled() int64 {
	if m != nil && m.DaisySled != nil {
		return *m.DaisySled
	}
	return 0
}

func (m *PocketRoses) GetSubmarineSaw() int64 {
	if m != nil && m.SubmarineSaw != nil {
		return *m.SubmarineSaw
	}
	return 0
}

func (m *PocketRoses) GetSmileLetter() bool {
	if m != nil && m.SmileLetter != nil {
		return *m.SmileLetter
	}
	return false
}

func (m *PocketRoses) GetIconHope() BullySunrise {
	if m != nil && m.IconHope != nil {
		return *m.IconHope
	}
	return BullySunrise_Sandals
}

func (m *PocketRoses) GetVanPurse() HopeArch {
	if m != nil && m.VanPurse != nil {
		return *m.VanPurse
	}
	return HopeArch_Mind
}

func (m *PocketRoses) GetMenuPaperclip() []string {
	if m != nil {
		return m.MenuPaperclip
	}
	return nil
}

func (m *PocketRoses) GetBeetlePoker() []string {
	if m != nil {
		return m.BeetlePoker
	}
	return nil
}

func (m *PocketRoses) GetWigPride() []string {
	if m != nil {
		return m.WigPride
	}
	return nil
}

func (m *PocketRoses) GetDivorceFair() DivorceFair {
	if m != nil && m.DivorceFair != nil {
		return *m.DivorceFair
	}
	return DivorceFair_Lawyer
}

func (m *PocketRoses) GetFlightParachute() []uint32 {
	if m != nil {
		return m.FlightParachute
	}
	return nil
}

func (m *PocketRoses) GetBeerRace() []uint32 {
	if m != nil {
		return m.BeerRace
	}
	return nil
}

func (m *PocketRoses) GetLoftQuarry() [][]byte {
	if m != nil {
		return m.LoftQuarry
	}
	return nil
}

func (m *PocketRoses) GetTaxiDivorce() [][]byte {
	if m != nil {
		return m.TaxiDivorce
	}
	return nil
}

func (m *PocketRoses) GetElectionButter() []uint32 {
	if m != nil {
		return m.ElectionButter
	}
	return nil
}

func (m *PocketRoses) GetBriefcaseBaboon() [][]byte {
	if m != nil {
		return m.BriefcaseBaboon
	}
	return nil
}

func (m *PocketRoses) GetMapShark() string {
	if m != nil && m.MapShark != nil {
		return *m.MapShark
	}
	return ""
}

func (m *PocketRoses) GetNetInterlude() bool {
	if m != nil && m.NetInterlude != nil {
		return *m.NetInterlude
	}
	return false
}

func init() {
	proto.RegisterEnum("main.DivorceFair", DivorceFair_name, DivorceFair_value)
	proto.RegisterEnum("main.HopeArch", HopeArch_name, HopeArch_value)
	proto.RegisterEnum("main.BullySunrise", BullySunrise_name, BullySunrise_value)
}
func NewPopulatedTypewriterPrison(r randyTypewriterprison, easy bool) *TypewriterPrison {
	this := &TypewriterPrison{}
	if r.Intn(10) != 0 {
		v1 := r.Intn(100)
		this.WineMessenger = make([]byte, v1)
		for i := 0; i < v1; i++ {
			this.WineMessenger[i] = byte(r.Intn(256))
		}
	}
	if r.Intn(10) != 0 {
		v2 := r.Intn(100)
		this.ShoelaceBeer = make([]byte, v2)
		for i := 0; i < v2; i++ {
			this.ShoelaceBeer[i] = byte(r.Intn(256))
		}
	}
	if r.Intn(10) != 0 {
		this.PocketRoses = NewPopulatedPocketRoses(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedTypewriterprison(r, 4)
	}
	return this
}

func NewPopulatedPocketRoses(r randyTypewriterprison, easy bool) *PocketRoses {
	this := &PocketRoses{}
	if r.Intn(10) != 0 {
		v3 := randStringTypewriterprison(r)
		this.ScarBusStop = &v3
	}
	if r.Intn(10) != 0 {
		v4 := r.Int63()
		if r.Intn(2) == 0 {
			v4 *= -1
		}
		this.BadgeShopping = &v4
	}
	if r.Intn(10) != 0 {
		v5 := r.Int63()
		if r.Intn(2) == 0 {
			v5 *= -1
		}
		this.DaisySled = &v5
	}
	if r.Intn(10) != 0 {
		v6 := r.Int63()
		if r.Intn(2) == 0 {
			v6 *= -1
		}
		this.SubmarineSaw = &v6
	}
	if r.Intn(10) != 0 {
		v7 := bool(r.Intn(2) == 0)
		this.SmileLetter = &v7
	}
	if r.Intn(10) != 0 {
		v8 := BullySunrise([]int32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}[r.Intn(11)])
		this.IconHope = &v8
	}
	if r.Intn(10) != 0 {
		v9 := HopeArch([]int32{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53}[r.Intn(54)])
		this.VanPurse = &v9
	}
	if r.Intn(10) != 0 {
		v10 := r.Intn(10)
		this.MenuPaperclip = make([]string, v10)
		for i := 0; i < v10; i++ {
			this.MenuPaperclip[i] = randStringTypewriterprison(r)
		}
	}
	if r.Intn(10) != 0 {
		v11 := r.Intn(10)
		this.BeetlePoker = make([]string, v11)
		for i := 0; i < v11; i++ {
			this.BeetlePoker[i] = randStringTypewriterprison(r)
		}
	}
	if r.Intn(10) != 0 {
		v12 := r.Intn(10)
		this.WigPride = make([]string, v12)
		for i := 0; i < v12; i++ {
			this.WigPride[i] = randStringTypewriterprison(r)
		}
	}
	if r.Intn(10) != 0 {
		v13 := DivorceFair([]int32{4, 5, 6, 9, 10, 11, 15, 21, 22}[r.Intn(9)])
		this.DivorceFair = &v13
	}
	if r.Intn(10) != 0 {
		v14 := r.Intn(100)
		this.FlightParachute = make([]uint32, v14)
		for i := 0; i < v14; i++ {
			this.FlightParachute[i] = r.Uint32()
		}
	}
	if r.Intn(10) != 0 {
		v15 := r.Intn(100)
		this.BeerRace = make([]uint32, v15)
		for i := 0; i < v15; i++ {
			this.BeerRace[i] = r.Uint32()
		}
	}
	if r.Intn(10) != 0 {
		v16 := r.Intn(100)
		this.LoftQuarry = make([][]byte, v16)
		for i := 0; i < v16; i++ {
			v17 := r.Intn(100)
			this.LoftQuarry[i] = make([]byte, v17)
			for j := 0; j < v17; j++ {
				this.LoftQuarry[i][j] = byte(r.Intn(256))
			}
		}
	}
	if r.Intn(10) != 0 {
		v18 := r.Intn(100)
		this.TaxiDivorce = make([][]byte, v18)
		for i := 0; i < v18; i++ {
			v19 := r.Intn(100)
			this.TaxiDivorce[i] = make([]byte, v19)
			for j := 0; j < v19; j++ {
				this.TaxiDivorce[i][j] = byte(r.Intn(256))
			}
		}
	}
	if r.Intn(10) != 0 {
		v20 := r.Intn(100)
		this.ElectionButter = make([]uint32, v20)
		for i := 0; i < v20; i++ {
			this.ElectionButter[i] = r.Uint32()
		}
	}
	if r.Intn(10) != 0 {
		v21 := r.Intn(100)
		this.BriefcaseBaboon = make([][]byte, v21)
		for i := 0; i < v21; i++ {
			v22 := r.Intn(100)
			this.BriefcaseBaboon[i] = make([]byte, v22)
			for j := 0; j < v22; j++ {
				this.BriefcaseBaboon[i][j] = byte(r.Intn(256))
			}
		}
	}
	if r.Intn(10) != 0 {
		v23 := randStringTypewriterprison(r)
		this.MapShark = &v23
	}
	if r.Intn(10) != 0 {
		v24 := bool(r.Intn(2) == 0)
		this.NetInterlude = &v24
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedTypewriterprison(r, 20)
	}
	return this
}

type randyTypewriterprison interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneTypewriterprison(r randyTypewriterprison) rune {
	return rune(r.Intn(126-43) + 43)
}
func randStringTypewriterprison(r randyTypewriterprison) string {
	v25 := r.Intn(100)
	tmps := make([]rune, v25)
	for i := 0; i < v25; i++ {
		tmps[i] = randUTF8RuneTypewriterprison(r)
	}
	return string(tmps)
}
func randUnrecognizedTypewriterprison(r randyTypewriterprison, maxFieldNumber int) (data []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		data = randFieldTypewriterprison(data, r, fieldNumber, wire)
	}
	return data
}
func randFieldTypewriterprison(data []byte, r randyTypewriterprison, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		data = encodeVarintPopulateTypewriterprison(data, uint64(key))
		v26 := r.Int63()
		if r.Intn(2) == 0 {
			v26 *= -1
		}
		data = encodeVarintPopulateTypewriterprison(data, uint64(v26))
	case 1:
		data = encodeVarintPopulateTypewriterprison(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		data = encodeVarintPopulateTypewriterprison(data, uint64(key))
		ll := r.Intn(100)
		data = encodeVarintPopulateTypewriterprison(data, uint64(ll))
		for j := 0; j < ll; j++ {
			data = append(data, byte(r.Intn(256)))
		}
	default:
		data = encodeVarintPopulateTypewriterprison(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return data
}
func encodeVarintPopulateTypewriterprison(data []byte, v uint64) []byte {
	for v >= 1<<7 {
		data = append(data, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	data = append(data, uint8(v))
	return data
}
