<< 
import (
  . "github.com/katydid/katydid/relapse/ast"
  "github.com/katydid/katydid/relapse/types"
  "github.com/gogo/protobuf/proto"
  "github.com/katydid/katydid/relapse/token"
  "strconv"
)

func newString(v interface{}) string {
  t := v.(*token.Token)
  return string(t.Lit)
}

func unquote(s1 string) string {
  s, err := strconv.Unquote(s1)
  if err != nil {
    return s1
  }
  return s
}

>>
