// Code generated by goderive DO NOT EDIT.

package main

// deriveHashStr returns the hash of the object.
func deriveHashStr(object string) uint64 {
	var h uint64
	for _, c := range object {
		h = 31*h + uint64(c)
	}
	return h
}
