// Code generated by funcs-gen.
// DO NOT EDIT!

package funcs

type lenFloat64s struct {
	E Float64s
}

func (this *lenFloat64s) Eval() int64 {
	return int64(len(this.E.Eval()))
}

func init() {
	Register("length", new(lenFloat64s))
}

type lenInt64s struct {
	E Int64s
}

func (this *lenInt64s) Eval() int64 {
	return int64(len(this.E.Eval()))
}

func init() {
	Register("length", new(lenInt64s))
}

type lenUint64s struct {
	E Uint64s
}

func (this *lenUint64s) Eval() int64 {
	return int64(len(this.E.Eval()))
}

func init() {
	Register("length", new(lenUint64s))
}

type lenBools struct {
	E Bools
}

func (this *lenBools) Eval() int64 {
	return int64(len(this.E.Eval()))
}

func init() {
	Register("length", new(lenBools))
}

type lenStrings struct {
	E Strings
}

func (this *lenStrings) Eval() int64 {
	return int64(len(this.E.Eval()))
}

func init() {
	Register("length", new(lenStrings))
}

type lenListOfBytes struct {
	E ListOfBytes
}

func (this *lenListOfBytes) Eval() int64 {
	return int64(len(this.E.Eval()))
}

func init() {
	Register("length", new(lenListOfBytes))
}

type lenString struct {
	E String
}

func (this *lenString) Eval() int64 {
	return int64(len(this.E.Eval()))
}

func init() {
	Register("length", new(lenString))
}

type lenBytes struct {
	E Bytes
}

func (this *lenBytes) Eval() int64 {
	return int64(len(this.E.Eval()))
}

func init() {
	Register("length", new(lenBytes))
}
