gengo:
	(cd ../../../../../../../ && protoc3 --gogo_out=src/github.com/katydid/katydid/relapse/mem/testproto/ -I=.:src/github.com/gogo/protobuf/protobuf:src/github.com/katydid/katydid/relapse/mem/testproto/ src/github.com/katydid/katydid/relapse/mem/testproto/Banana.proto)
	

